### ISSUE TITLE
Colored format?

### ISSUE THREAD

**Issue by yo1995** [nguyenvanduocit/Wox.Plugin.Emoji#1]
I would like to make it a colored emoji search result list with svg icons or pngs. Since I found the black-white sketch does not seem to be clear enough. Do you like this idea? If so, I'll try to PR someday.

**Comment by nguyenvanduocit** [comment]
It's very cool, let's do it

**Comment by yo1995** [comment]
![](https://github.com/yo1995/Wox.Plugin.Emoji/raw/master/preview.png)
I've done most of that. Could check it out in https://github.com/yo1995/Wox.Plugin.Emoji 
Tomorrow I'll try to wrap them up and submit a PR.
It might need some adjustment from you, since I found the build version does not have 'Image/copy.png'.  Maybe you could help to include the newly added the 'Icons' directory to building dependencies.
Also fixed some typos. 😀
